---
kind: pipeline
name: default


steps:
  - name: sync_push
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/telegrambot.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - push
    commands:
      - git remote add github $REPO_REMOTE
      - git push github $DRONE_BRANCH

  - name: sync_tag
    image: alpine/git:1.0.7
    environment:
      REPO_REMOTE: https://github.com/fewensa/telegrambot.git
    volumes:
      - name: git_credentials
        path: /root/.git-credentials
      - name: git_config
        path: /root/.gitconfig
    when:
      event:
        - tag
    commands:
      - git remote add github $REPO_REMOTE
      - git fetch origin
      - git push github $DRONE_TAG

volumes:
  - name: git_credentials
    host:
      path: /data/mount/git/.git-credentials
  - name: git_config
    host:
      path: /data/mount/git/.gitconfig


---
kind: pipeline
name: publish

steps:
  - name: publish
    image: rust:1.33-slim
    volumes:
      - name: rustruntime
        path: /drone/src/target
      - name: cargo
        path: /root/.cargo
    commands:
      - apt update
      - apt install -y libssl-dev pkg-config
      - sh -f /root/.cargo/credentials
      - cargo publish

volumes:
  - name: cargo
    host:
      path: /data/mount/cargo
  - name: rustruntime
    host:
      path: /data/mount/rustruntime/telegrambot

trigger:
  event:
    - tag


---
kind: pipeline
name: build

steps:
  - name: build
    image: rust:1.33-slim
    volumes:
      - name: rustruntime
        path: /drone/src/target
    commands:
      - apt update
      - apt install -y libssl-dev pkg-config
      - cargo package

volumes:
  - name: rustruntime
    host:
      path: /data/mount/rustruntime/telegrambot


trigger:
  branch:
    - master
